
export const ADD_TO_TOTAL = 'ADD_TO_TOTAL';
export const SUBTRACT_FROM_TOTAL = 'SUBTRACT_FROM_TOTAL';
export const RESET_TOTAL = 'RESET_TOTAL';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const TRY_SUBMIT_ORDER = 'TRY_SUBMIT_ORDER';
export const ORDER_SUBMITTED = 'ORDER_SUBMITTED';
export const RESET_ORDER_STATUS = 'RESET_ORDER_STATUS';
export const ORDER_PROCESSING = 'ORDER_PROCESSING';
export const SUBMIT_ORDER_FAILED = 'SUBMIT_ORDER_FAILED';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_CHANGE_REDIRECT_PATH = 'AUTH_CHANGE_REDIRECT_PATH';