export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const ADD_TO_TOTAL = 'ADD_TO_TOTAL';
export const SUBTRACT_FROM_TOTAL = 'SUBTRACT_FROM_TOTAL';

